### ISSUE TITLE
Numpy built in datatype deprecation in accelerated engine(s?)

### ISSUE THREAD

**Issue by Nordicus** [ptycho/ptypy#467]
Numpy has deprecated the numpy.bool datatype in favour of the standard python bool datatype. This deprecation expired as of numpy version 1.24 ([https://numpy.org/devdocs/release/1.24.0-notes.html](https://numpy.org/devdocs/release/1.24.0-notes.html)) and the deprecation was warned about from 1.20 [https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations).

Using DM_pycuda gives an error with numpy from version 1.24.
Presumably this error exists with other pycuda engines.
A workaround for any new users after the workshop is after installing from the pycuda dependencies file is manually downgrading with `conda install -c conda-forge numpy=1.23` but going forward the reference to these deprecated types should probably be changed.

To cause this issue I was working from exercise 5 from the workshop tutorials, and the cell code is as follows:

```
import ptypy
import ptypy.utils as u

ptypy.load_gpu_engines("cuda")

p = u.Param()
p.verbose_level = "interactive"
p.io = u.Param()
p.io.rfile = None
p.io.autosave = u.Param(active=False)
p.io.interaction = u.Param(active=False)

p.scans = u.Param()
p.scans.MF = u.Param()
p.scans.MF.name = "Full"
p.scans.MF.data= u.Param()
p.scans.MF.data.name = "MoonFlowerScan"
p.scans.MF.data.shape = 128
p.scans.MF.data.num_frames = 200
p.scans.MF.data.save = None
p.scans.MF.data.density = 0.2
p.scans.MF.data.photons = 1e8
p.scans.MF.data.psf = 0.

# Define reconstruction engines
p.engines = u.Param()

# Difference Map (DM) engine
p.engines.engine00 = u.Param()
p.engines.engine00.name = "DM_pycuda"
p.engines.engine00.numiter = 80

P = ptypy.core.Ptycho(p,level=5)
```

And the error is then:

```
Full: loading data for scan MF (161 diffraction frames, 161 PODs, 1 probe(s) and 1 object(s))
Full: loading data for scan MF (reformatting probe/obj/exit)
Full: loading data for scan MF (initializing probe/obj/exit)
DM_pycuda: initializing engine

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 63
     60 p.engines.engine01.scale_precond = True
     61 p.engines.engine01.scale_probe_object = 1.
---> 63 P = ptypy.core.Ptycho(p,level=5)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/core/ptycho.py:383, in Ptycho.__init__(self, pars, level, **kwargs)
    381     self.init_engine()
    382 if level >= 5:
--> 383     self.run()
    384     self.finalize()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/core/ptycho.py:763, in Ptycho.run(self, label, epars, engine)
    761 self.runtime.allstop = None
    762 for engine in self.engines.values():
--> 763     self.run(engine=engine)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/core/ptycho.py:648, in Ptycho.run(self, label, epars, engine)
    646 ilog_message('%s: initializing engine' %engine.p.name)
    647 with LogTime(self.p.io.benchmark == 'all') as t:
--> 648     engine.initialize()
    649 if (self.p.io.benchmark == 'all') and parallel.master: self.benchmark.engine_init += t.duration
    651 # One .prepare() is always executed, as Ptycho may hold data

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/engines/base.py:153, in BaseEngine.initialize(self)
    150     if not model.__class__ in self.SUPPORTED_MODELS:
    151         raise Exception('Model %s not supported by engine %s' % (model.__class__,self.p.name))
--> 153 self.engine_initialize()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda_stream.py:49, in _ProjectionEngine_pycuda_stream.engine_initialize(self)
     48 def engine_initialize(self):
---> 49     super().engine_initialize()
     50     self.qu_htod = cuda.Stream()
     51     self.qu_dtoh = cuda.Stream()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda.py:95, in _ProjectionEngine_pycuda.engine_initialize(self)
     92     # interpolated shift kernel
     93     self.ISK = InterpolatedShiftKernel(queue=self.queue)
---> 95 super().engine_initialize()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/base/engines/projectional_serial.py:137, in _ProjectionEngine_serial.engine_initialize(self)
    135 super().engine_initialize()
    136 self._reset_benchmarks()
--> 137 self._setup_kernels()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda_stream.py:55, in _ProjectionEngine_pycuda_stream._setup_kernels(self)
     53 def _setup_kernels(self):
---> 55     super()._setup_kernels()
     56     ex_mem = 0
     57     mag_mem = 0

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda.py:146, in _ProjectionEngine_pycuda._setup_kernels(self)
    144 log(4, "Setting up PropagationKernel")
    145 kern.PROP = PropagationKernel(aux, geo.propagator, self.queue, self.p.fft_lib)
--> 146 kern.PROP.allocate()
    147 kern.resolution = geo.resolution[0]
    149 if self.do_position_refinement:

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/kernels.py:64, in PropagationKernel.allocate(self)
     61 else:
     62     self._tmp = aux
---> 64 self._fft1 = FFT(self._tmp, self.queue,
     65                  pre_fft=self._p.pre_fft,
     66                  post_fft=self._p.post_fft,
     67                  symmetric=True,
     68                  forward=True)
     69 self._fft2 = FFT(self._tmp, self.queue,
     70                  pre_fft=self._p.pre_ifft,
     71                  post_fft=self._p.post_ifft,
     72                  symmetric=True,
     73                  forward=False)
     74 if self._do_crop_pad:

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/fft.py:18, in FFT.__init__(self, array, queue, inplace, pre_fft, post_fft, symmetric, forward)
     16 from pycuda import gpuarray
     17 ## reikna
---> 18 from reikna import cluda
     19 api = cluda.cuda_api()
     20 thr = api.Thread(queue)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/__init__.py:1
----> 1 from reikna.cluda.array_helpers import concatenate, roll

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/__init__.py:4
      1 from reikna.cluda.api_discovery import cuda_id, ocl_id, api_ids, supports_api, \
      2     supported_api_ids, get_api, cuda_api, ocl_api, any_api
      3 from reikna.cluda.api_tools import find_devices
----> 4 from reikna.cluda.kernel import Module, Snippet
      7 class OutOfResourcesError(Exception):
      8     """
      9     Thrown by :py:meth:`~reikna.cluda.api.Thread.compile_static`
     10     if the provided ``local_size`` is too big, or one cannot be found.
     11     """

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/kernel.py:7
      5 import reikna.helpers as helpers
      6 from reikna.helpers import template_for, template_from, template_def, extract_signature_and_value
----> 7 from reikna.cluda import dtypes
     10 TEMPLATE = template_for(__file__)
     13 def render_prelude(thr, fast_math=False, constant_arrays=None):

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/dtypes.py:208
    205     _register_dtype(numpy.complex64, "float2")
    206     _register_dtype(numpy.complex128, "double2")
--> 208 _fill_dtype_registry()
    211 def ctype(dtype):
    212     """
    213     For a built-in C type, returns a string with the name of the type.
    214     """

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/dtypes.py:187, in _fill_dtype_registry(respect_windows)
    184 import sys
    185 import platform
--> 187 _register_dtype(numpy.bool, "bool")
    188 _register_dtype(numpy.int8, "char")
    189 _register_dtype(numpy.uint8, "unsigned char")

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'bool'

```

**Comment by daurer** [comment]
Thanks @Nordicus for catching this, the problem actually occurs in the reikna package that we use in the acceleration engines as default for the FFT. As suggested, downgrading to `numpy==1.23` is probably the best fix for now. Otherwise, you could also try using a different FFT, e.g. `p.engines.engine00.fft_lib="cuda"` or  `p.engines.engine00.fft_lib="skcuda"`. 

But going forward, we might need to walk away from reikna FFT as the default. @bjoernenders what do you think?

**Comment by bjoernenders** [comment]
Hi, I think there is a fix in with reikna. 
See https://github.com/fjarri/reikna/commit/f996fad4d7a85f8d6c8d9a7a6ac6e0983a5346ac. But we don't know when that fix will be released. We could either add build instruction for reikna (like pip install), switch the default,or downgrade numpy in the deps. I'd say we downgrade numpy for a few weeks to see how fast reikna can get the fix out. If that doesn't happen we switch the default to an alternative FFT (I'd say skcuda). Long term we need to see if the cupy version of our code is the one to keep.
Bjoern

**Comment by Nordicus** [comment]
I don't think that a Reikna fix is likely to be released particularly quickly. reikna's release history on their [website](https://reikna.publicfields.net/en/latest/history.html) on [pypi](https://pypi.org/project/reikna/#history), and on [conda-forge](https://anaconda.org/conda-forge/reikna) all indicate a slow release pattern. I wouldn't expect a fix soon. I think that if we want to keep up with newer versions of numpy (which for performance and compatibility reasons, I would encourage) then changing the default FFT would be a wise choice. Where should I look for changing the default FFT to try and make the fix?

**Comment by Nordicus** [comment]
> Otherwise, you could also try using a different FFT, e.g. `p.engines.engine00.fft_lib="cuda"` or `p.engines.engine00.fft_lib="skcuda"`.

I've now tried this, and it doesn't fix the issue. It seems that reikna is still being loaded despite using cuda or skcuda as the fft lib.
```
AttributeError                            Traceback (most recent call last)
Cell In[4], line 34
     31 p.engines.engine00.numiter = 80
     32 p.engines.engine00.fft_lib="skcuda"
---> 34 P = ptypy.core.Ptycho(p,level=5)
     36 # Display the results
     37 fig = ptypy.utils.plot_client.figure_from_ptycho(P)
```

**Comment by bjoernenders** [comment]
Hi @Nordicus I looked at the code and it shouldn't happen. Could you paste the entire error trace here, please. Thanks!

**Comment by Nordicus** [comment]
Code cell:
```
import ptypy
import ptypy.utils as u

ptypy.load_gpu_engines("cuda")

p = u.Param()
p.verbose_level = "interactive"
p.io = u.Param()
p.io.rfile = None
p.io.autosave = u.Param(active=False)
p.io.interaction = u.Param(active=False)

p.scans = u.Param()
p.scans.MF = u.Param()
p.scans.MF.name = "Full"
p.scans.MF.data= u.Param()
p.scans.MF.data.name = "MoonFlowerScan"
p.scans.MF.data.shape = 128
p.scans.MF.data.num_frames = 200
p.scans.MF.data.save = None
p.scans.MF.data.density = 0.2
p.scans.MF.data.photons = 1e8
p.scans.MF.data.psf = 0.

# Define reconstruction engines
p.engines = u.Param()

# Difference Map (DM) engine
p.engines.engine00 = u.Param()
p.engines.engine00.name = "DM_pycuda"
p.engines.engine00.numiter = 80
p.engines.engine00.fft_lib="skcuda"

P = ptypy.core.Ptycho(p,level=5)

# Display the results
fig = ptypy.utils.plot_client.figure_from_ptycho(P)
```

Cell output (including stack trace): 
```
Full: loading data for scan MF (161 diffraction frames, 161 PODs, 1 probe(s) and 1 object(s))
Full: loading data for scan MF (reformatting probe/obj/exit)
Full: loading data for scan MF (initializing probe/obj/exit)
DM_pycuda: initializing engine

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 34
     31 p.engines.engine00.numiter = 80
     32 p.engines.engine00.fft_lib="skcuda"
---> 34 P = ptypy.core.Ptycho(p,level=5)
     36 # Display the results
     37 fig = ptypy.utils.plot_client.figure_from_ptycho(P)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/core/ptycho.py:383, in Ptycho.__init__(self, pars, level, **kwargs)
    381     self.init_engine()
    382 if level >= 5:
--> 383     self.run()
    384     self.finalize()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/core/ptycho.py:763, in Ptycho.run(self, label, epars, engine)
    761 self.runtime.allstop = None
    762 for engine in self.engines.values():
--> 763     self.run(engine=engine)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/core/ptycho.py:648, in Ptycho.run(self, label, epars, engine)
    646 ilog_message('%s: initializing engine' %engine.p.name)
    647 with LogTime(self.p.io.benchmark == 'all') as t:
--> 648     engine.initialize()
    649 if (self.p.io.benchmark == 'all') and parallel.master: self.benchmark.engine_init += t.duration
    651 # One .prepare() is always executed, as Ptycho may hold data

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/engines/base.py:153, in BaseEngine.initialize(self)
    150     if not model.__class__ in self.SUPPORTED_MODELS:
    151         raise Exception('Model %s not supported by engine %s' % (model.__class__,self.p.name))
--> 153 self.engine_initialize()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda_stream.py:49, in _ProjectionEngine_pycuda_stream.engine_initialize(self)
     48 def engine_initialize(self):
---> 49     super().engine_initialize()
     50     self.qu_htod = cuda.Stream()
     51     self.qu_dtoh = cuda.Stream()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda.py:95, in _ProjectionEngine_pycuda.engine_initialize(self)
     92     # interpolated shift kernel
     93     self.ISK = InterpolatedShiftKernel(queue=self.queue)
---> 95 super().engine_initialize()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/base/engines/projectional_serial.py:137, in _ProjectionEngine_serial.engine_initialize(self)
    135 super().engine_initialize()
    136 self._reset_benchmarks()
--> 137 self._setup_kernels()

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda_stream.py:55, in _ProjectionEngine_pycuda_stream._setup_kernels(self)
     53 def _setup_kernels(self):
---> 55     super()._setup_kernels()
     56     ex_mem = 0
     57     mag_mem = 0

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda.py:146, in _ProjectionEngine_pycuda._setup_kernels(self)
    144 log(4, "Setting up PropagationKernel")
    145 kern.PROP = PropagationKernel(aux, geo.propagator, self.queue, self.p.fft_lib)
--> 146 kern.PROP.allocate()
    147 kern.resolution = geo.resolution[0]
    149 if self.do_position_refinement:

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/kernels.py:64, in PropagationKernel.allocate(self)
     61 else:
     62     self._tmp = aux
---> 64 self._fft1 = FFT(self._tmp, self.queue,
     65                  pre_fft=self._p.pre_fft,
     66                  post_fft=self._p.post_fft,
     67                  symmetric=True,
     68                  forward=True)
     69 self._fft2 = FFT(self._tmp, self.queue,
     70                  pre_fft=self._p.pre_ifft,
     71                  post_fft=self._p.post_ifft,
     72                  symmetric=True,
     73                  forward=False)
     74 if self._do_crop_pad:

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/fft.py:18, in FFT.__init__(self, array, queue, inplace, pre_fft, post_fft, symmetric, forward)
     16 from pycuda import gpuarray
     17 ## reikna
---> 18 from reikna import cluda
     19 api = cluda.cuda_api()
     20 thr = api.Thread(queue)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/__init__.py:1
----> 1 from reikna.cluda.array_helpers import concatenate, roll

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/__init__.py:4
      1 from reikna.cluda.api_discovery import cuda_id, ocl_id, api_ids, supports_api, \
      2     supported_api_ids, get_api, cuda_api, ocl_api, any_api
      3 from reikna.cluda.api_tools import find_devices
----> 4 from reikna.cluda.kernel import Module, Snippet
      7 class OutOfResourcesError(Exception):
      8     """
      9     Thrown by :py:meth:`~reikna.cluda.api.Thread.compile_static`
     10     if the provided ``local_size`` is too big, or one cannot be found.
     11     """

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/kernel.py:7
      5 import reikna.helpers as helpers
      6 from reikna.helpers import template_for, template_from, template_def, extract_signature_and_value
----> 7 from reikna.cluda import dtypes
     10 TEMPLATE = template_for(__file__)
     13 def render_prelude(thr, fast_math=False, constant_arrays=None):

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/dtypes.py:208
    205     _register_dtype(numpy.complex64, "float2")
    206     _register_dtype(numpy.complex128, "double2")
--> 208 _fill_dtype_registry()
    211 def ctype(dtype):
    212     """
    213     For a built-in C type, returns a string with the name of the type.
    214     """

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/reikna/cluda/dtypes.py:187, in _fill_dtype_registry(respect_windows)
    184 import sys
    185 import platform
--> 187 _register_dtype(numpy.bool, "bool")
    188 _register_dtype(numpy.int8, "char")
    189 _register_dtype(numpy.uint8, "unsigned char")

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'bool'
```

**Comment by daurer** [comment]
@Nordicus could you try importing the "skcuda" FFT module directly:
`from ptypy.accelerate.cuda_pycuda.cufft import FFT_skcuda as FFT`
Do you get any error when trying to import this module?

**Comment by bjoernenders** [comment]
I don't think that is the problem. Somehow the fft_lib choice is ignored. But I can't point my finger at it. This used to work fine. And "skcuda" is the right choice.

**Comment by bjoernenders** [comment]
Let me scratch that comment. If skcuda can't be loaded it should spit out a warning, but I don't see that in the printout that you provided. So Benedikt's suggestion is correct. Try import the skcuda fft. 

If skcuda import fails for the PropagationKernel it will default to reikna (with the warning). Maybe the warnings are suppressed in your session.

**Comment by Nordicus** [comment]
Yes. Importing the skcuda FFT directly fails and it appears that a warning must have been suppressed.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from ptypy.accelerate.cuda_pycuda.cufft import FFT_skcuda as FFT

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/cufft.py:1
----> 1 import skcuda.fft as cu_fft
      2 from skcuda.fft import cufft as cufftlib
      3 from pycuda import gpuarray

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/skcuda/fft.py:20
     15 from .cufft import CUFFT_COMPATIBILITY_NATIVE, \
     16      CUFFT_COMPATIBILITY_FFTW_PADDING, \
     17      CUFFT_COMPATIBILITY_FFTW_ASYMMETRIC, \
     18      CUFFT_COMPATIBILITY_FFTW_ALL
     19 from . import cudart
---> 20 from . import misc
     22 class Plan:
     23     """
     24     CUFFT plan class.
     25 
   (...)
     60         indicates whether the caller intends to allocate and manage the work area
     61     """

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/skcuda/misc.py:637
    633 diff.cache = {}
    636 # List of available numerical types provided by numpy:
--> 637 num_types = [np.typeDict[t] for t in \
    638              np.typecodes['AllInteger']+np.typecodes['AllFloat']]
    640 # Numbers of bytes occupied by each numerical type:
    641 num_nbytes = dict((np.dtype(t),t(1).nbytes) for t in num_types)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/skcuda/misc.py:637, in <listcomp>(.0)
    633 diff.cache = {}
    636 # List of available numerical types provided by numpy:
--> 637 num_types = [np.typeDict[t] for t in \
    638              np.typecodes['AllInteger']+np.typecodes['AllFloat']]
    640 # Numbers of bytes occupied by each numerical type:
    641 num_nbytes = dict((np.dtype(t),t(1).nbytes) for t in num_types)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'typeDict'
```
The error is the same for importing the cuda fft directly:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 from ptypy.accelerate.cuda_pycuda.cufft import FFT_cuda as FFT

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/ptypy/accelerate/cuda_pycuda/cufft.py:1
----> 1 import skcuda.fft as cu_fft
      2 from skcuda.fft import cufft as cufftlib
      3 from pycuda import gpuarray

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/skcuda/fft.py:20
     15 from .cufft import CUFFT_COMPATIBILITY_NATIVE, \
     16      CUFFT_COMPATIBILITY_FFTW_PADDING, \
     17      CUFFT_COMPATIBILITY_FFTW_ASYMMETRIC, \
     18      CUFFT_COMPATIBILITY_FFTW_ALL
     19 from . import cudart
---> 20 from . import misc
     22 class Plan:
     23     """
     24     CUFFT plan class.
     25 
   (...)
     60         indicates whether the caller intends to allocate and manage the work area
     61     """

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/skcuda/misc.py:637
    633 diff.cache = {}
    636 # List of available numerical types provided by numpy:
--> 637 num_types = [np.typeDict[t] for t in \
    638              np.typecodes['AllInteger']+np.typecodes['AllFloat']]
    640 # Numbers of bytes occupied by each numerical type:
    641 num_nbytes = dict((np.dtype(t),t(1).nbytes) for t in num_types)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/skcuda/misc.py:637, in <listcomp>(.0)
    633 diff.cache = {}
    636 # List of available numerical types provided by numpy:
--> 637 num_types = [np.typeDict[t] for t in \
    638              np.typecodes['AllInteger']+np.typecodes['AllFloat']]
    640 # Numbers of bytes occupied by each numerical type:
    641 num_nbytes = dict((np.dtype(t),t(1).nbytes) for t in num_types)

File /ceph/users/uyy37579/conda_envs/ptypy_pycuda/lib/python3.9/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'typeDict'
```

It seems that this is another [numpy deprecation](https://numpy.org/devdocs/release/1.21.0-notes.html) that seems to have expired, silently this time. Both imports work with numpy version 1.23.

**Comment by bjoernenders** [comment]
Ok if none of our propagators work with numpy>1.23 then we need to fix the numpy version for now.

**Comment by bjoernenders** [comment]
So Reikna put in the patch and released 0.8.0. It's already on pypi but not yet on conda forge.

**Comment by daurer** [comment]
Reikna 0.8.0 is out on conda-forge now: https://anaconda.org/conda-forge/reikna.

**Comment by Nordicus** [comment]
Ok, with numpy v1.24 and reikna v0.8.0:
``from ptypy.accelerate.cuda_pycuda.cufft import FFT_cuda as FFT`` fails (with the previous typedict error)
``from ptypy.accelerate.cuda_pycuda.cufft import FFT_skcuda as FFT`` fails (with the previous typedict error)

Whether ``p.engines.engine00.fft_lib="cuda"``, ``p.engines.engine00.fft_lib="skcuda"`` or neither are used the pycuda version works and runs a reconstruction. I suspect that whichever FFT engine is chosen it is failing as Björn suggested and defaulting to the reikna FFT. Either way, I think that while it might be worth looking into why the loading a specific FFT fails, this issue can be closed.

**Comment by daurer** [comment]
@Nordicus thanks for the update. Yes, our default choice is the Reikna FFT so if any of the other FFTs fail at import, it will fall back to Reikna FFT - which seems to work again with latest versions on conda-forge 👍 

The typedict error seems to be an issue with the scikit-cuda package causing issues for both` fft_lib="cuda"` and `fft_lib="skcuda"` because `skcuda.fft` is imported at module level in `https://github.com/ptycho/ptypy/blob/master/ptypy/accelerate/cuda_pycuda/cufft.py`. I made a separate issue for this #471
